name: huge_listview
description: A performant list with any number of items.
version: 2.0.12
homepage: https://github.com/deakjahn/huge_listview

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.2.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

funding:
  - https://buymeacoffee.com/deakjahn

topics:
  - flutter
  - listview